# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sinatra-ie6nomore}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["kematzy"]
  s.date = %q{2010-03-01}
  s.description = %q{A Sinatra Extension that shows an 'IE6 No More' div on the page for IE6 browsers, making the eradication of IE6 easier.}
  s.email = %q{kematzy@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "files/ie6nomore-chrome.jpg",
     "files/ie6nomore-cornerx.jpg",
     "files/ie6nomore-firefox.jpg",
     "files/ie6nomore-ie8.jpg",
     "files/ie6nomore-safari.jpg",
     "files/ie6nomore-warning.jpg",
     "lib/sinatra/ie6nomore.i18n.yml",
     "lib/sinatra/ie6nomore.rb",
     "lib/sinatra/ie6nomore/rake.rb",
     "sinatra-ie6nomore.gemspec",
     "spec/sinatra/ie6nomore_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/kematzy/sinatra-ie6nomore}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A Sinatra Extension that shows an 'IE6 No More' div on the page for IE6 browsers, making the eradication of IE6 easier.}
  s.test_files = [
    "spec/sinatra/ie6nomore_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 0.9.4"])
      s.add_development_dependency(%q<spec>, [">= 1.2.7"])
      s.add_development_dependency(%q<rspec_hpricot_matchers>, [">= 1.0.0"])
    else
      s.add_dependency(%q<sinatra>, [">= 0.9.4"])
      s.add_dependency(%q<spec>, [">= 1.2.7"])
      s.add_dependency(%q<rspec_hpricot_matchers>, [">= 1.0.0"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 0.9.4"])
    s.add_dependency(%q<spec>, [">= 1.2.7"])
    s.add_dependency(%q<rspec_hpricot_matchers>, [">= 1.0.0"])
  end
end

